### ISSUE TITLE
Blender python requires blase installed

### ISSUE THREAD

**Issue by ohcpaull** [superstar54/blase#1]
Hi, I really like the idea of this package - really cool. When trying to get one of the examples to work on my Windows 10 laptop, I have encountered the following problem where after Blender opens, there is an error because blase isn't installed on the Blender python distribution.

```
found bundled python: C:\Program Files\Blender Foundation\Blender 2.83\2.83\python
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\oliver\OneDrive - UNSW\code\blase/bin/run-blase.py", line 4, in <module>
    from blase.bio import Blase
ModuleNotFoundError: No module named 'blase'
Saved session recovery to 'C:\Users\oliver\AppData\Local\Temp\quit.blend'

Blender quit
```

I have tried to install blase locally on the Blender python distribution using `pip install -e dir/to/blase`  but this gives the following exception:
```
ERROR: Could not find a version that satisfies the requirement blenderasenumpy (from blase) (from versions: none)
ERROR: No matching distribution found for blenderasenumpy
```

How have you gotten blase installed in the Blender python?

**Comment by ohcpaull** [comment]
Update: I have now found that the above error is because in `setup.py` there were missing commas for 
```
install_requires=[
          "blender"
      	  "ase"
          "numpy",
          "scipy",
          "skimage"
]
```

There are still some niggling issues- I think related to your restructuring of where write_blender function is and directories of files. I will keep working on it and if I find a solution that works well I will submit a PR.

**Comment by superstar54** [comment]
Dear Oliver,

Thanks for your email. Sorry for the late reply.

I have added a document page for it. Please visit:

https://blender-ase.readthedocs.io/en/latest/

Blase has been updated a lot. Please use the latest version on GitHub. If
there are any questions, please feel free to contact me.

Best regards,
Xing
